### ISSUE TITLE
CPU Rewrite Mode

### ISSUE THREAD

**Issue by sden054** [dex6/m37512_reset#1]
It seems that we need to enter to the "CPU Rewrite Mode" before using "Read/Program/Erase".

**Comment by dex6** [comment]
Thanks for your input and interest in this project. Unfortunately, I'm not able to develop and test this software anymore due to lack of hardware and time. Basing on my old notes, I've written a real readme file which you may find useful. Please feel free to fork and modify.

**Comment by sden054** [comment]
Thank you for README! It gave me understanding that datasheet describes flash memory programming from the MCU itself. And that we have to use BOOT mode: "connect pins 12, 9 and 43 of M37512 together".
I will give it a try.
Thank you for your work!
